name = "BSplines"
uuid = "8759ff0c-cd99-11e8-1c1c-d94a817e6fcc"
authors = ["Stefanos Carlström <stefanos.carlstrom@gmail.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
